#!/bin/sh
### BEGIN INIT INFO
# Provides:          check-updates
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Check for updates
# Description:       Checks for any available radiodan app updates
### END INIT INFO

set -e

export PATH=$PATH:/usr/local/bin

/usr/local/bin/updater check --workspace=/opt/radiodan/updates --target=/opt/radiodan/apps
