#!/bin/sh
#/etc/init.d/radiodan-physical-ui

### BEGIN INIT INFO
# Provides:          radiodan-physical-ui
# Required-Start:    $remote_fs $syslog $network $rabbitmq-server
# Required-Stop:     $remote_fs $syslog $network $rabbitmq-server
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Radiodan physical interface
# Description:       Radiodan physical interface
### END INIT INFO

export PATH="/opt/node/bin:$PATH"

case "$1" in
  start)
  mkdir -p /var/run/radiodan
  exec forever --sourceDir=/opt/radiodan/physical-ui -p /var/run/radiodan-physical-ui ./bin/ui > /var/log/radiodan/physical-ui.log 2>&1
  ;;
stop)
  exec forever stop --sourceDir=/opt/radiodan/physical-ui ./bin/ui
  ;;
*)
  echo "Usage: /etc/init.d/radiodan-physical-ui {start|stop}"
  exit 1
  ;;
esac

exit 0
