#!/bin/sh

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export LOG_LEVEL=debug
export BBC_SERVICES_URL=http://bbc-services-api.herokuapp.com

case "$1" in
  start)
  exec forever start --pidFile=/var/run/radiodan/radiodan-server.pid --sourceDir=/opt/radiodan/server -o /var/log/radiodan/server.access.log -e /var/log/radiodan/server.error.log ./bin/server /opt/radiodan/magic/config/radiodan-config.json
  ;;

  stop)
  exec forever stop --sourceDir=/opt/radiodan/magic ./bin/server
  ;;
esac

exit 0
